name: Test custom runner

on:
  pull_request:

jobs:
  test-custom-runner:
    runs-on: bbp
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run a few shell commands
        run: |
          hostname
          git status
          ls
          pwd
