name: Commit message validation

on:
  pull_request:

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate commit messages
        run: |
          echo "Deepening shallow clone to ${{ github.event.pull_request.commits }} commits"
          git fetch --deepen=${{ github.event.pull_request.commits }}
          pip install gitpython
          python ./.github/workflows/validate-commit-message.py
