name: Commit message validation

on:
  pull_request:

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validate commit messages
        id: commit-message-validator
        continue-on-error: true
        run: |
          echo "Deepening shallow clone to ${{ github.event.pull_request.commits }} commits"
          git fetch --deepen=$((${{ github.event.pull_request.commits }} - 1))
          pip install gitpython
          python ./.github/workflows/validate-commit-message.py

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: faulty_commits.txt
        if: ${{ steps.commit-message-validator.outputs.faulty-commits }}=true
